class AllDistrictClass {
  static final districtList = [
    {"id": "bagerhat", "name": "Bagerhat"},
    {"id": "bandarban", "name": "Bandarban"},
    {"id": "barguna", "name": "Barguna"},
    {"id": "barisal", "name": "Barisal"},
    {"id": "bhola", "name": "Bhola"},
    {"id": "bogra", "name": "Bogra"},
    {"id": "brahmanbaria", "name": "Brahmanbaria"},
    {"id": "chandpur", "name": "Chandpur"},
    {"id": "chatai_nawabganj", "name": "Chapai Nawabganj"},
    {"id": "chattogram", "name": "Chattogram"},
    {"id": "chuadanga", "name": "Chuadanga"},
    {"id": "comilla", "name": "Comilla"},
    {"id": "coxs_bazar", "name": "Cox's Bazar"},
    {"id": "dhaka", "name": "Dhaka"},
    {"id": "dinajpur", "name": "Dinajpur"},
    {"id": "faridpur", "name": "Faridpur"},
    {"id": "feni", "name": "Feni"},
    {"id": "gaibandha", "name": "Gaibandha"},
    {"id": "gazipur", "name": "Gazipur"},
    {"id": "gopalganj", "name": "Gopalganj"},
    {"id": "habiganj", "name": "Habiganj"},
    {"id": "jamalpur", "name": "Jamalpur"},
    {"id": "jashore", "name": "Jashore"},
    {"id": "jhalokathi", "name": "Jhalokathi"},
    {"id": "jhenaidah", "name": "Jhenaidah"},
    {"id": "joypurhat", "name": "Joypurhat"},
    {"id": "khagrachhari", "name": "Khagrachhari"},
    {"id": "khulna", "name": "Khulna"},
    {"id": "kishoreganj", "name": "Kishoreganj"},
    {"id": "kurigram", "name": "Kurigram"},
    {"id": "kushtia", "name": "Kushtia"},
    {"id": "lakshmipur", "name": "Lakshmipur"},
    {"id": "lalmonirhat", "name": "Lalmonirhat"},
    {"id": "madaripur", "name": "Madaripur"},
    {"id": "magura", "name": "Magura"},
    {"id": "manikganj", "name": "Manikganj"},
    {"id": "meherpur", "name": "Meherpur"},
    {"id": "moulvibazar", "name": "Moulvibazar"},
    {"id": "munshiganj", "name": "Munshiganj"},
    {"id": "mymensingh", "name": "Mymensingh"},
    {"id": "naogaon", "name": "Naogaon"},
    {"id": "narail", "name": "Narail"},
    {"id": "narayanganj", "name": "Narayanganj"},
    {"id": "narsingdi", "name": "Narsingdi"},
    {"id": "natore", "name": "Natore"},
    {"id": "netrokona", "name": "Netrokona"},
    {"id": "nilphamari", "name": "Nilphamari"},
    {"id": "noakhali", "name": "Noakhali"},
    {"id": "pabna", "name": "Pabna"},
    {"id": "panchagarh", "name": "Panchagarh"},
    {"id": "patuakhali", "name": "Patuakhali"},
    {"id": "pirojpur", "name": "Pirojpur"},
    {"id": "rajbari", "name": "Rajbari"},
    {"id": "rajshahi", "name": "Rajshahi"},
    {"id": "rangamati", "name": "Rangamati"},
    {"id": "rangpur", "name": "Rangpur"},
    {"id": "satkhira", "name": "Satkhira"},
    {"id": "shariatpur", "name": "Shariatpur"},
    {"id": "sherpur", "name": "Sherpur"},
    {"id": "sirajganj", "name": "Sirajganj"},
    {"id": "sunamganj", "name": "Sunamganj"},
    {"id": "sylhet", "name": "Sylhet"},
    {"id": "tangail", "name": "Tangail"},
    {"id": "thakurgaon", "name": "Thakurgaon"},
  ];
}

class BusinessTypeClass {
  static final businessTypeList = [
    {"id": "distributor", "name": "Distributor"},
    {"id": "diller", "name": "Diller"},
    {"id": "sub-diller", "name": "Sub-Diller"},
    {"id": "retailer", "name": "Retailer"},
  ];
}

class PartyTypeClass {
  static final partyTypeList = [
    {"id": "retailer", "name": "Retailer"},
    {"id": "dealer", "name": "Dealer"},
    {"id": "wholesaler", "name": "Wholesaler"},
  ];
}

